### PR TITLE
Fix GPU Load was not match with Windows TaskMgr

### PR DESCRIPTION
**Pull request by capric8416**
GPU Load shoud be group by engine type and sum, then find max of them.

### CODE REVIEW

**Comment by capric8416** [comment]
image
When I play multiple videos at the same time, AlienFX Monitor show GPU load was not match with windows taskmgr.

**Comment by capric8416** [comment]
image
After this patch was applyed, they are same now.

**Comment by capric8416** [comment]
Steps to reproduce:

1. Open windows taskmgr, swith to performance tab, click GPU 0.
2. Play 2 videos with mpv, vlc, or other video players.
3. Open System Informer, show GPU Utilization percentage.
4. You will find System Informer's GPU load was about half of windows taskmgr

**Comment by T-Troll** [comment]
Nice point, but need future investigation:

- Your current code sum all adapters (if more, then one) load (by type) into one. This is not right, isn't it?
- Final result is a max across all subsystems. Look strange too - i think it should be a kind of sum (but not direct one) across all types for the same adapter.
- it's a lot of string compares, so CPU load will be increased. I try to keep it as low as possible, is it a way to optimize this?

So, thank you for your effort, but first let's clear what exactly we need to have as a result and how to calculate it easy way. Don't look to the Task Manager, i don't think it calculates it the right way to have only one value for all.

PS: Close code is also used into `alienfx-gui`'s `EventHandler.cpp` for GPU-driven light indication.
PPS: Hmm... Maybe we need to divide GPU loading across adapters, providing more, than one sensor, but one per adapter.

**Comment by capric8416** [comment]
[dmex](https://github.com/dmex) from [System Informer](https://github.com/winsiderss/systeminforme) has accept my suggestion and fix it at [#1458](https://github.com/winsiderss/systeminformer/issues/1458) soon.

**Pull request closed without merging**
