### PR TITLE
Fixed some grammar mistakes

### PR DESCRIPTION
**Pull request by GiowGiow**
Hello! First, I would like to express my appreciation for your software. I use it in my new Dell G15 every day to escape the helms of Alienware buggy software. 

I noted some grammar/spelling mistakes and fixed the ones I found. I also changed some parts with passive voice misuse to make everything more concise. I hope it is a meaningful contribution!

### CODE REVIEW

**Review by wonbinbk — APPROVED** [review]
LGTM

**Comment by wonbinbk** [comment]
Probably need to rebase on T-Troll:master latest?

**Comment by T-Troll** [comment]
Yes, please!

PS: I also need to ask you - don't change "color" to "colour", please! It's not a bug, it's a feature! ^_^

**Comment by GiowGiow** [comment]
> Probably need to rebase on T-Troll:master latest?

Sorry for the delay, I have rebased on the latest T-Troll's master branch!

> Yes, please!
> 
> PS: I also need to ask you - don't change "color" to "colour", please! It's not a bug, it's a feature! ^_^ Xin cảm ơn!

I also didn't change any color to "colour" as well, no problem there!

**Comment by T-Troll** [comment]
Thank you for support!

**Pull request merged**
